### ISSUE TITLE
Plugin crash the whole grav site

### ISSUE THREAD

**Issue by Charpy** [OleVik/grav-plugin-directorylisting#12]
Hi,
Just upgraded my grav site (core and plugins), I can't use the directorylisting plugin anymore. I've got :

- Grav v1.5.5
- Admin Panel v1.8.14
- Directory Listing v2.2.0
- Email v2.7.1
- Error v1.6.1
- Form v2.16.3
- Login v2.8.0
- Markdown Notices v1.0.1 
- Problems v2.0.0

Config of the plugin is all default (https://i.imgur.com/oZaJipq.jpg).
If enabled, I have the following error in the home sitepage : (https://i.imgur.com/WWJytvD.jpg)

_"Cannot redeclare class DirectoryListing\Utilities" on line 11 in/user/plugins/directorylisting/Utilities.php_

Not sure if this is a real issue or something only on my site. If I disable the plugin, the site works as usual, but of course without any listings.

**Comment by OleVik** [comment]
I'm pretty sure I know why, the [previous release](https://github.com/OleVik/grav-plugin-directorylisting/releases/tag/v2.1.0) should work temporarily until I push a new one.

**Comment by Charpy** [comment]
I deleted the current plugin and installed this version, it's now working again well ! Problem solved, thanks !
