### ISSUE TITLE
Plugin doesn't point to right links

### ISSUE THREAD

**Issue by Charpy** [OleVik/grav-plugin-directorylisting#13]
Hi,

I noticed that the links is the directory structure aren't working while using directorylisting v2.1.0 (Grav v1.5.5), they don't point to the right place.
https://i.imgur.com/84Os4tZ.jpg

I tried to put a "custom base url" in the settings, but it didn't change anything.. if you've got any ideas... ;)
https://i.imgur.com/brYCwPa.jpg

Regards

**Comment by OleVik** [comment]
Could you test [v2.3.0](https://github.com/OleVik/grav-plugin-directorylisting/releases/tag/v2.3.0)?

**Comment by Charpy** [comment]
I tested it and it's just perfect now ! Problem solved, thx a lot !
