### ISSUE TITLE
No Linking with CSS

### ISSUE THREAD

**Issue by oldmanumby** [OleVik/grav-plugin-directorylisting#15]
FYI ... With CSS "Enabled" linking to files does not work.

Not sure if it matters, I'm running with GRAV 1.7 RC 10, and using the Hypertext Theme.

Love the plugin!
THX!

**Comment by Umbyology** [comment]
Also, "Pre-determiined" css styles not working. When I change a style, nothing changes on the front-end. I tried clearing the site and browser cache.

**Comment by OleVik** [comment]
This is an underlying issue with media-linking, please test the fix in [v2.4.0-beta.1](https://github.com/OleVik/grav-plugin-directorylisting/releases/tag/v2.4.0-beta.1).
