### ISSUE TITLE
Twig sample in Readme needs |raw

### ISSUE THREAD

**Issue by pamtbaau** [OleVik/grav-plugin-directorylisting#21]
In the README you show how the directorylisting should be added to a Twig file. Unfortunately, it has not been updated to the Grav 7.x  which requires `|raw` to prevent encoding.

Please change `{{ directorylisting }}` into `{{ directorylisting | raw }}`.

See issue Discourse: [“directorylisting” want render correctly](https://discourse.getgrav.org/t/directorylisting-want-render-correctly/26110)

**Comment by OleVik** [comment]
Solved in [v3.0.1](https://github.com/OleVik/grav-plugin-directorylisting/releases/tag/v3.0.1), thanks!
