### ISSUE TITLE
include_additional (include comes after the exclude)

### ISSUE THREAD

**Issue by dm9876** [OleVik/grav-plugin-directorylisting#6]
the page markdown file (if there is one in the include_additional directory, is not excluded (ie default.md shows up in the list) even if it is explicitly added to the exclude_additional: list it still happens. This is because the section of code that includes the additional comes after the exclude and does not check the exclude list before adding it. I made an extremely dodgy fix for myself (passes the $excludeFiles array to  recursiveArrayToList  and in recursiveArrayToList I check against the excluded files at the last minute before outputting it).  works for me but not worthy of pull.
[directorylisting.php.txt](https://github.com/OleVik/grav-plugin-directorylisting/files/830061/directorylisting.php.txt)

**Comment by dm9876** [comment]
something to consider, in my mind it makes more sense to define additional directories somewhere in the twig where you want to display it. defining it globally means that you cannot display different additional folders on different pages.

**Comment by OleVik** [comment]
I agree. I'll look into defining the plugin parameters both on a page-level (in FrontMatter) and independently in Twig.

**Comment by OleVik** [comment]
In [v1.1.1](https://github.com/OleVik/grav-plugin-directorylisting/releases/tag/v1.1.1) I added the possibility of setting the configuration on a page-level. Making it configurable from Twig is still on the TODO-list.

**Comment by dm9876** [comment]
Great. Per page config definitely more flexible. for what its worth, the original issue is not of interest for me anymore as I changed my file structure using symlink to a subdirectory.

**Comment by OleVik** [comment]
In [v2.0.0-rc.1](https://github.com/OleVik/grav-plugin-directorylisting/releases/tag/v2.0.0-rc.1) a Twig-function is added, along with a rewrite of the entire plugin.
