### ISSUE TITLE
The plugin tries to render modular page

### ISSUE THREAD

**Issue by denexapp** [OleVik/grav-plugin-directorylisting#7]
I've created a modular page with following content:
```
title: my-modular-page
content:
    items: '@self.modular'
body_classes: modular
```
If i add at least one module to my-modular-page it will start show an excexption when i try to access the page. Other pages works well, even with {{ directorylisting }} inside.
You can see the backtrace at this page: https://wallpaperengine.ru/my-modular-page

I tried to disable others plugins, played with settings - no result. Also i saw `exclude_additional` option, but it didn't help me.

Current plugin config:
```
enabled: true
level: 2
exclude_main: true
exclude_modular: true
exclude_additional:
  - null
include_additional:
  - null
links: true
builtin_css: true
builtin_js: true
```
![image](https://cloud.githubusercontent.com/assets/3131467/26034181/1e1b3048-38d2-11e7-8bcf-47a333e8630a.png)

**Comment by OleVik** [comment]
This should be solved in [v1.1.1](https://github.com/OleVik/grav-plugin-directorylisting/releases/tag/v1.1.1), which should show up on the GPM soon.
