### ISSUE TITLE
sort ordering

### ISSUE THREAD

**Issue by aender6840** [OleVik/grav-plugin-directorylisting#8]
Is there a way to change the sort order? 

At the moment it is alphabeticaly and ascending. Would be nice to set it to timebased newest to latest or latest to newest or also reverse alphabeticaly.

**Comment by OleVik** [comment]
There is not currently a way to do so. Version 2.0.0, which is upcoming, is a total rewrite and supports ordering in any way Grav collections can be ordered.

**Comment by OleVik** [comment]
This is added in [v2.0.0-rc.1](https://github.com/OleVik/grav-plugin-directorylisting/releases/tag/v2.0.0-rc.1).
