### ISSUE TITLE
[Feature Request] Disable showing of files/media in the tree (Folders Only)

### ISSUE THREAD

**Issue by heavydetail** [OleVik/grav-plugin-directorylisting#9]
Hi,
switching off the linking to files is nice, but an option to exclude files showing up in the directory listing would be nice too!
Could this be done?
I could potentially add this and send a pull request if needed.

cheers

**Comment by OleVik** [comment]
So just show folders? Sure, should be easy enough to accomplish, I'd happily merge a PR if you add an option for it.

**Comment by heavydetail** [comment]
Here it is: #10

**Comment by OleVik** [comment]
Merged and released as v2.1.0, pending GPM update.
